---
nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: https://mskelton.dev/yarn-outdated/v2

yarnPath: .yarn/releases/yarn-3.3.1.cjs

npmScopes:
  opentalk:
    npmRegistryServer: https://git.opentalk.dev/api/v4/projects/434/packages/npm/

npmRegistries:
  //gitlab.example.com/api/v4/projects/<your_project_id>/packages/npm/:
    npmAlwaysAuth: true
